### ISSUE TITLE
KDiscordIPC cannot load junixsocket-native for amd64-Linux

### ISSUE THREAD

**Issue by Wyvest** [cbyrneee/KDiscordIPC#5]
KDiscordIPC throws
`
Caused by: SocketConnectionException(reason=Could not load native library junixsocket-native for architecture amd64-Linux)
	at dev.cbyrne.kdiscordipc.socket.impl.UnixSystemSocket.connect(UnixSystemSocket.kt:47)
	at dev.cbyrne.kdiscordipc.socket.DiscordSocket.connect(DiscordSocket.kt:76)
	at dev.cbyrne.kdiscordipc.DiscordIPC.connect(DiscordIPC.kt:95)
`
when trying to connect.

This error occurs on my Kubuntu 21.04 machine and someone else's Arch Linux machine

**Comment by caoimhebyrne** [comment]
Will update to the latest JUnixSocket in the next few days, should resolve this issue.

**Comment by Wyvest** [comment]
moment

**Comment by caoimhebyrne** [comment]
I've been busy over the last few days, I will get to this soon.

**Comment by Wyvest** [comment]
for some strange reason this still occurs? Even downgrading doesn't work, which is stange as the issue that mentions it has that as a temporary fix

**Comment by caoimhebyrne** [comment]
Not my issue. Can't do anything about it, sorry.

**Comment by Wyvest** [comment]
Actually, it may be because of https://github.com/kohlschutter/junixsocket/issues/93 . perhaps the jitpack should be used instead of mavenCentral?

**Comment by Wyvest** [comment]
nevermind.

**Comment by Wyvest** [comment]
Strange, running the selftest jar seems to work. Perhaps it's an issue on my end?
